### PR TITLE
feat: improve current haystack integration

### LINKED ISSUE #4: [FEATURE] Improve current Haystack Integration
- Modify some code to avoid metadata bug
- Add some fields for thought and observation (when a tool is used by the agent)
- Clean some code

### PR DESCRIPTION
**Pull request by sdiazlor**
Closes #4 and #5 .

TO DO:

* [x]  Update tests

NOTES:
- Allow customized questions and guidelines
- Solve metadata bug (dictionary was not initialized at each agent call) and empty tool_name metadata
- Some refactoring to avoid having everything in the __init__ function
- Add transcript as a field when a tool is used (I thought that it was not useful or easy to use as metadata)
- Add time durations similarly to other integrations
- Modify pyproject with a different installation for each Haystack version. Both installed in the same environment is not possible.
- Update the documentation

### CODE REVIEW

**Review by davidberenstein1957 — COMMENTED** [review]
Looks good, 2 small remarks.
- maybe we can set the pyproject to haystack<2 because 2 does not work right? 
- perhaps we can simpify the OpenAI token import behavior

**Comment by davidberenstein1957** [comment]
@sdiazlor after this, you can also create a PR to add the same tutorial to our docs.argilla.io within the integrations section.

**Comment by sdiazlor** [comment]
@davidberenstein1957 Regarding the pyproject I removed the optional dependency for Haystack 2.x and left 1.x, so that it can be easily added when available. Note that <2 can not be used as the pypi packages are different (farm-haystack for 1.x and haystack-ai for 2.x)

**Comment by davidberenstein1957** [comment]
@sdiazlor can you communicate and coordinate the tutorial and updates with the people from haystack?

**Review by davidberenstein1957 — APPROVED** [review]
LFTM

**Pull request merged**
